### ISSUE TITLE
Proper serialization registration

### ISSUE THREAD

**Issue by lokalmatador** [lokalmatador/ades#1]
Replace usage of 

`ar.template register_type<DMPContainer>();`

with 

`BOOST_CLASS_EXPORT( ades::DMPContainer);`
`BOOST_CLASS_EXPORT_GUID(ades::DMPContainer, "DMPContainer")`

**Comment by r1d1** [comment]
Should be either
BOOST_CLASS_EXPORT( ades::DMPContainer);
or
BOOST_CLASS_EXPORT_GUID(ades::DMPContainer, "DMPContainer")
(for the sake of precision)
http://www.boost.org/doc/libs/1_46_1/libs/serialization/doc/special.html

**Comment by lokalmatador** [comment]
Doesn't work with BOOST_CLASS_EXPORT
